[apply-phab] Check the format of LLVM reviews

diff --git a/symlinks/.bin/apply-phab b/symlinks/.bin/apply-phab
--- a/symlinks/.bin/apply-phab
+++ b/symlinks/.bin/apply-phab
@@ -35,6 +35,9 @@ if [ -z ${review+x} ]; then
     echo "${PROGNAME} needs a review number"
     usage
     exit 1
+elif [[ ! ${review} =~ ^(D|d)[0-9]+$ ]]; then
+    echo "Invalid review number format: '${review}'"
+    exit 1
 fi
 
 if [ -z ${directory+x} ]; then
